london_bicycle_assignment:
  outputs:
    dev:
      dataset: 'london_bicycle_assignment'
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: 'oauth' # OAuth uses gcloud auth application-default login. 'service-account' requires JSON key file.
      priority: interactive 
      project: 'my-project-dsai-3'
      threads: 1
      type: bigquery
  target: dev